# Generated by Django 5.0 on 2023-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('Certificate_title', models.CharField(max_length=255)),
                ('Signature', models.CharField(max_length=255)),
            ],
        ),
    ]
