# Generated by Django 5.0 on 2023-12-22 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_Genrator', '0002_certificate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Certificate_title',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='Signature',
            new_name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='full_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
