# Generated by Django 5.0 on 2023-12-22 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_Genrator', '0003_rename_certificate_title_certificate_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
