# Generated by Django 5.0 on 2023-12-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_Genrator', '0004_alter_certificate_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='unique_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
